package ExceptionHandling;

public class User {
          // try catch and finally 
	public static void main(String[] args) {
		System.out.println("A");
		System.out.println("A");
		System.out.println("A");

		try {
			int i = 9 / 3;
			System.out.println("hello world");
		} 
		catch (ArithmeticException e) {
			System.out.println("AE is coming...");
			e.printStackTrace();
		}
		finally {
			System.out.println("im in finally block...");
		}
		
		System.out.println("--------");
		
		try {
			int p = 10/0;//throwing the exception
		}
		finally {
			System.out.println("im in 2nd finally block...");

		}
		
		System.out.println("bye!");
		
		System.out.println("--------");


		
		
		
		
		
		
		
		
	}

}
